apiVersion: v1
kind: Service
metadata:
  name: {{ include "examplechart.fullname" . }}-frontend
  labels:
{{ include "examplechart.labels" . | indent 4 }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "examplechart.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
