FROM openjdk:8 as build-stage

WORKDIR /app
RUN git clone https://github.com/docker-hy/spring-example-project.git
WORKDIR spring-example-project
RUN ./mvnw package

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=build-stage /app/spring-example-project/target /app/target

RUN adduser -D spring && \
    chown -R spring . 

USER spring

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "./target/docker-example-1.1.3.jar"]


