version: '3'

services:
  backend-example-docker:
    image: backend
    build: ../../part1/ex1-12/backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on: 
      - db

  frontend-example-docker:
    image: frontend
    build: ../../part1/ex1-12/frontend
    ports:
      - 5000:5000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  proxy:
    image: jwilder/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

